name: Lab 7 Tests

on:
  push

jobs:
  lab-7-tests:
    runs-on: ubuntu-latest
    container: 
      # by claude 3.7 sonnet thinking
      image: ghcr.io/puppeteer/puppeteer:latest
      options: --shm-size=2gb --user root

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: install stuff
        run: |
          npm install

      - name: lets not change the given code from template
        run: |
          cat > jest-puppeteer.config.js<<EOF
          module.exports = {
            launch: {
              headless: true,
              args: [
                '--no-sandbox',
                '--disable-setuid-sandbox'
              ]
            }
          }
          EOF

      - name: Run tests
        run: |
          npm run test
